source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
swift_version='3.0'

def shared_pods
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON', '~> 3.0'
  pod 'SVProgressHUD'
end

target 'MTDataAPI' do
    shared_pods
end

target 'MTDataAPITests' do
    shared_pods
end
