# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 2.0'
pod 'SwiftyJSON', :git => "https://github.com/SwiftyJSON/SwiftyJSON.git", :branch => 'xcode7'
pod 'SVProgressHUD'
